решена 3 задача
js-tasks-ru/jsbasic-20220418_khozhaevaregina pull request #7
Opened 2022-05-26 10:28 UTC by regikho

2022-05-26 10:29 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-05-26 11:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-26 11:42 UTC, koalex requested changes
нужно решить 6 модуль

2022-05-27 09:20 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-05-30 12:25 UTC, koalex approved these changes

2022-05-30 12:26 UTC, merged